### ISSUE TITLE
Entrar na mailing list e assinar o termo

### ISSUE THREAD

**Issue by MarcosNBJ** [GCES-Kubernetes/Wiki#10]
O primeiro passo para fazer parte da comunidade é entrar na [mailing list](https://groups.google.com/forum/#!forum/kubernetes-dev), através da qual os membros são incluídos nos eventos do calendário e recebem instruções e comunicados importantes. Em seguida, é necessário assinar o *Contributor License Agreement*, que assinala concordância com a licensa do projeto e dá os direitos sobre as contribuições adicionadas. Para ler as instruções e assinar o termo basta acessar [aqui](https://github.com/kubernetes/community/blob/master/CLA.md)

**Comment by satsfy** [comment]
Feito!

**Comment by MarcosNBJ** [comment]
Todos cumpriram ambos.
