### ISSUE TITLE
Definir issues candidatas a serem realizadas na sprint 2

### ISSUE THREAD

**Issue by MarcosNBJ** [GCES-Kubernetes/Wiki#7]
Explorar as issues dos repositórios disponíveis em [kubernetes](https://github.com/kubernetes) e em [kubernetes-sigs](https://github.com/kubernetes-sigs). As que parecerem viáveis de serem iniciadas na sprint 2 deverão ser referenciadas na Wiki.
Issues de documentação, tradução de documentos e melhorias que não requerem o entendimento de um grande contexto são boas dicas.

**Comment by MarcosNBJ** [comment]
Tradução da documentação para português https://github.com/kubernetes/website/issues/13939

**Comment by satsfy** [comment]
Estou em processo de conversa com o Katz para avaliar essa issue: https://github.com/kubernetes/ingress-nginx/issues/7344.

Aparentemente, está stale há um mês. Vou conversar com ele para ver se podemos pegar ela.

**Comment by satsfy** [comment]
Outra possibilidade: https://github.com/kubernetes-sigs/gateway-api/issues/446

**Comment by satsfy** [comment]
Outra: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2136 (parece simples e sem contexto necessário)

**Comment by satsfy** [comment]
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1585

**Comment by gabrielalbino** [comment]
Achei uma que pode ser boa!
https://github.com/kubernetes/kubernetes/issues/92402
